name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
     -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
     - 
        name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
     - 
        name: Create Docker Image 
        run: docker build . --file Dockerfile --tag crudrestapi:$(date +%s)    
     -
        name: Push docker image to dockerhub 
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/crud-rest
